spring:
  application:
    name: bank-account
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/bank_account}
    auto-index-creation: false   # overridden to true in local and docker profiles

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
